crudpro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls'))
]

tasks/urls.py
# tasks/urls.py

from django.urls import path, re_path
from . import views

# namespace
app_name = 'tasks'

urlpatterns = [
    path('create/', views.task_create, name='task_create'),
    path('', views.task_list, name='task_list'),
    re_path(r'^(?P<pk>\d+)/$', views.task_detail, name='task_detail'),
    re_path(r'^(?P<pk>\d+)/update/$', views.task_update, name='task_update'),
    re_path(r'^(?P<pk>\d+)/delete/$', views.task_delete, name='task_delete'),

]

tasks/models.py
# tasks/models.py

from django.db import models
from datetime import datetime,date

class Status(models.TextChoices):
    UNSTARTED = 'u', "Not started yet"
    ONGOING = 'o', "Ongoing"
    FINISHED = 'f', "Finished"


class Task(models.Model):
    name = models.CharField(verbose_name="Task name", max_length=65, unique=True)
    status = models.CharField(verbose_name="Task status", max_length=10, choices=Status.choices)
    date = models.DateField("(mm/dd/yy)",auto_now_add=False, auto_now=False ,blank=True,null=True)
    timestramp=models.DateField(auto_now_add=True, auto_now=False ,blank=True)
    def __str__(self):
        return self.name

# tasks/forms.py
from .models import Task
from django import forms

class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = "__all__"

tasks/forms.py
#-*- coding:utf-8 -*-
from .models import Task
from django import forms

class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = "__all__"

tasks/views.py
# tasks/views.py

from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from .models import Task
from .forms import TaskForm

# Create your views here.

# Create a task
def task_create(request):
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse("tasks:task_list"))
    else:
        form = TaskForm()

    return render(request, "tasks/task_form.html", { "form": form, })


# Retrieve task list
def task_list(request):
    tasks = Task.objects.all()
    return render(request, "tasks/task_list.html", { "tasks": tasks,})


# Retrieve a single task
def task_detail(request, pk):
    task = get_object_or_404(Task, pk=pk)
    return render(request, "tasks/task_detail.html", { "task": task, })


# Update a single task
def task_update(request, pk):
    task_obj = get_object_or_404(Task, pk=pk)
    if request.method == 'POST':
        form = TaskForm(instance=task_obj, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse("tasks:task_detail", args=[pk,]))
    else:
        form = TaskForm(instance=task_obj)

    return render(request, "tasks/task_form.html", { "form": form, "object": task_obj})


# Delete a single task
def task_delete(request, pk):
    task_obj = get_object_or_404(Task, pk=pk)
    task_obj.delete()
    return redirect(reverse("tasks:task_list"))

tasks/templates/tasks/task_detail.html
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="widtd=device-widtd, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <style>
        table,td,th{
            border: 2px solid black ;
             border-collapse: collapse; 
             
             padding:10px;
             margin:5px;
        }
        body{
         background-color:green;
     }
    </style>
    <title>Task Details</title>
  </head>
  <body>
   <div class="container" style="position:absolute; left:0; right:0; top: 50%; transform: translateY(-50%); -ms-transform: translateY(-50%); -moz-transform: translateY(-50%); -webkit-transform: translateY(-50%); -o-transform: translateY(-50%);">
      <div class="row justify-content-center">
          <div class="col-md-10 col-lg-9 col-xl-9 col-xxl-7">
              <div class="card shadow-lg o-hidden border-0 my-5">
                  <div class="card-body p-0">
                      <div class="row">
                          <div class="col-lg-12">
                              <div class="p-5">
                                  <div class="text-center">
                                    <h1 class="text-center">Task Details</h1>
                                    <center><div class="mt-2">
                                        <table>
                                            <tr>
                                            <th>Title</th>
                                            <th>Status</th>
                                            <th>Update</th>
                                            <th>Delete</th>
                                            </tr>
                                            <tr>
                                                <td> {{ task.name }}</td>
                                                <td>{{ task.get_status_display }}</td>
                                                <td><a class="btn btn-primary" href="{% url 'tasks:task_update' task.id %}">Update</a></td>
                                                <td><a class="btn btn-primary" href="{% url 'tasks:task_delete' task.id %}">Delete</a></td>
                                        </table>
                                         <a class="btn btn-primary mt-3" href="{% url 'tasks:task_list' %}">View All Tasks</a>
                                            <a class="btn btn-primary mt-3" href="{% url 'tasks:task_create'%}">New Task</a>
                                        
                                    </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
</center>

</body>
</html>

tasks/templates/tasks/task_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="widtd=device-widtd, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    
    <title>{% if object %}Edit Task {% else %} Create New Task {% endif %}</title>
    <style>
        body{
            background-color:green;
        }
    </style>
</head>
<body>
    <div class="container" style="position:absolute; left:0; right:0; top: 50%; transform: translateY(-50%); -ms-transform: translateY(-50%); -moz-transform: translateY(-50%); -webkit-transform: translateY(-50%); -o-transform: translateY(-50%);">
        <div class="row justify-content-center">
            <div class="col-md-10 col-lg-9 col-xl-9 col-xxl-7">
                <div class="card shadow-lg o-hidden border-0 my-5">
                    <div class="card-body p-0">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="p-5">
                                    <div class="text-center">
                               <h3>{% if object %}Edit Task {% else %} Create New Task {% endif %}</h3>
                                  <form action="" method="post" enctype="multipart/form-data">
                                     {% csrf_token %}
                                     {{ form.as_p }}
                                 <p><input type="submit" class="btn btn-success" value="Submit"></p>
                                   </form>
                                   </div>
                                 </div>
                                </div>
                             </div>
                           </div>
                         </div>
                        </div>
                       </div>
              </body>
      </html>

tasks/templates/tasks/task_list.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="widtd=device-widtd, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <style>
        table,td,th{
            border: 2px solid black ;
             border-collapse: collapse; 
             
             padding:10px;
             margin:5px;
        }
        body{
         background-color:green;
     }
    </style>
    <title>Task List</title>
  </head>
  <body>
   <div class="container" style="position:absolute; left:0; right:0; top: 50%; transform: translateY(-50%); -ms-transform: translateY(-50%); -moz-transform: translateY(-50%); -webkit-transform: translateY(-50%); -o-transform: translateY(-50%);">
      <div class="row justify-content-center">
          <div class="col-md-10 col-lg-9 col-xl-9 col-xxl-7">
              <div class="card shadow-lg o-hidden border-0 my-5">
                  <div class="card-body p-0">
                      <div class="row">
                          <div class="col-lg-12">
                              <div class="p-5">
                                  <div class="text-center">
                                    <h1 class="text-center">List of Tasks</h1>
                                    <center><div class="mt-2">
                                        {% for task in tasks %}
                                        <table>
                                                <thead>
                                                    <th>S.No</th>
                                                    <th>Title</th>
                                                    <th>Status</th>
                                                    <th>Date</th>
                                                    <th>Update</th>
                                                    <th>Delete</th>
                                                </thead>
                                                <tbody>
                                                   
                                                   <tr>
                                                       <td>{{ forloop.counter }}</td> <td>{{ task.name }}</td> <td>{{ task.get_status_display }}</td><td> {{ task.date }}</td>
                                                       <td><a class="btn btn-primary" href="{% url 'tasks:task_update' task.id %}">Update</a></td>
                                                       <td><a class="btn btn-primary" href="{% url 'tasks:task_delete' task.id %}">Delete</a></td>
                                                   </tr>
                                                  
                                                </tbody>
                                              </table>
                                              {% endfor %}
                                              <p> <a class="btn btn-primary mt-3" href="{% url 'tasks:task_create' %}"> Add A New Task</a></p>
                                    </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>


    
    
</center>

</body>
</html>